#version 430

layout(local_size_x = 1, local_size_y = 1) in;

uniform int Dm;

struct Chunk {
	int linked_list;
	float brightness;
};

restrict buffer ssbo_grid {
    Chunk chunks[];
};

void main() {
	vec2 pixel_coords = gl_GlobalInvocationID.xy / float(Dm);
	
	float brightness = length(1. - pixel_coords * 2.);
	brightness *= pixel_coords.y;

	chunks[gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * Dm].brightness = 0.;//brightness;
}